---
- hosts: all
  sudo: true
  vars:
    document_root: /app
  handlers:
    - name: reload nginx
      service: name=nginx state=reloaded

  pre_tasks:
    - name: update apt cache
      apt: update_cache=yes
  roles:
    - webserver
