---
- name: install nginx
  apt: name=nginx state=present

- name: Copy across new virtual host
  template: 
	src=virtual-hosts.conf.j2 
	dest=/etc/nginx/sites-available/vagrant.conf
- name: Remove default virtual host
  file:
    path=/etc/nginx/sites-enabled/default.conf
    state=absent
- name: Enable new vagrant virtual host
  file:
    src=/etc/nginx/sites-available/vagrant.conf
    dest=/etc/nginx/sites-enabled/vagrant.conf
    state=link
- name: reload nginx
  service: name=nginx state=reloaded
  notify:
    - reload nginx
